#!/bin/sh

set -e

case "$1" in
	remove|upgrade|remove-in-favour|deconfigure-in-favour)
		#
		# do here pre removes
		#
		echo "remove flugbuch2 from apache"
		a2dissite /etc/apache2/sites-available/flugbuch2
		;;
	failed-upgrade)
		;;
esac

exit 0
