#!/bin/sh

set -e

case "$1" in
	remove|upgrade|remove-in-favour|deconfigure-in-favour)
		#
		# do here pre removes
		#
		echo "remove flugbuch2 from apache"
		a2dissite flugbuch2.local
		/etc/init.d/apache2 reload
		;;
	failed-upgrade)
		;;
esac

exit 0
